default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecomap_development
  username: lxnotes
  password: lxnotespass2016

test:
  <<: *default
  database: ecomap_test
  username: lxnotes
  password: lxnotespass2016

production:
  <<: *default
  database: ecomap_production
  username: ecomap
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
