default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/development.sqlite3

development:
  <<: *default
  database: ecomap_development

test:
  <<: *default
  database: ecomap_test

production:
  <<: *default
  database: ecomap_production
  username: ecomap
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
